server:
  port: 8080
  ssl:
    enabled: true
    key-alias: localhost_ssl
    key-store-password: password
    key-store: classpath:localhost-ssl.p12
    key-store-type: PKCS12 
  
spring:
  application:
    name: api-gateway
  
    
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
          
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"          
      