server:
  port: 6060
    
spring:
  application:
    name: service-two
  
info:
  app:
    name: ${spring.application.name}
  build:
    artifactId:@project.artifactId@
    groupId:@project.groupId@
  java:
    version:@java.version@    
  

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka    
      

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"        